import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

const babyChecklistStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.pinkBg,
    padding: 16,
  },
  header: {
    backgroundColor: Colors.white,
    padding: 24,
    borderRadius: 20,
    marginBottom: 20,
    shadowColor: Colors.pinkDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: Colors.pinkBorder,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    color: Colors.pink,
    textAlign: 'center',
    marginBottom: 8,
    textShadowColor: Colors.pinkShadowSoft,
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  subtitle: {
    fontSize: 16,
    color: Colors.purple,
    textAlign: 'center',
    marginBottom: 20,
    lineHeight: 22,
  },

  progressContainer: { marginBottom: 20 },
  progressBar: {
    height: 12,
    backgroundColor: Colors.purpleLight,
    borderRadius: 10,
    overflow: 'hidden',
    shadowColor: Colors.purple,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  progressFill: {
    height: '100%',
    backgroundColor: Colors.pink,
    borderRadius: 10,
    shadowColor: Colors.pink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  progressText: {
    fontSize: 14,
    color: Colors.purple,
    textAlign: 'center',
    marginTop: 12,
    fontWeight: '600',
  },

  categoryTabsContainer: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    marginBottom: 20,
    shadowColor: Colors.pinkDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: Colors.pinkBorder,
  },

  // categoryTabs: {
  //   flexDirection: 'row',
  //   flexWrap: 'wrap',
  //   padding: 16,
  // },
  categoryTabs: {
    flexDirection: 'row',   // כמו שהיה
    flexWrap: 'wrap',
    justifyContent: 'flex-end', // יישור לשול הימני
    padding: 16,
  },
  categoryTab: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    margin: 4,
    borderRadius: 25,
    backgroundColor: Colors.pinkBg,
    borderWidth: 2,
    borderColor: Colors.pinkLight,
    shadowColor: Colors.pinkDeep,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  categoryTabActive: {
    backgroundColor: Colors.pink,
    borderColor: Colors.pink,
    shadowColor: Colors.pink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },


  // רקע/מסגרת לפי קטגוריות
  categoryTabAll:       { backgroundColor: Colors.blueBg,   borderColor: Colors.blue },
  categoryTabClothing:  { backgroundColor: Colors.pinkLight, borderColor: Colors.pink },
  categoryTabFeeding:   { backgroundColor: Colors.orangeBg, borderColor: Colors.orange },
  categoryTabSleep:     { backgroundColor: Colors.greenBg,  borderColor: Colors.green },
  categoryTabHygiene:   { backgroundColor: Colors.purpleLight, borderColor: Colors.purple },
  categoryTabSafety:    { backgroundColor: Colors.redBg,    borderColor: Colors.red },
  categoryTabTransport: { backgroundColor: Colors.tealBg,   borderColor: Colors.teal },
  categoryTabToys:      { backgroundColor: Colors.amberBg,  borderColor: Colors.amber },
  categoryTabMedical:   { backgroundColor: Colors.limeBg,   borderColor: Colors.lime },
  categoryTabOther:     { backgroundColor: Colors.grayBg,   borderColor: Colors.gray },

  categoryTabText: {
    fontSize: 14,
    color: Colors.purple,
    fontWeight: '600',
  },
  categoryTabTextActive: { color: Colors.white, fontWeight: 'bold' },

  // צבעי טקסט לקטגוריות
  categoryTabTextAll:       { color: Colors.blue },
  categoryTabTextClothing:  { color: Colors.pink },
  categoryTabTextFeeding:   { color: Colors.orange },
  categoryTabTextSleep:     { color: Colors.green },
  categoryTabTextHygiene:   { color: Colors.purple },
  categoryTabTextSafety:    { color: Colors.red },
  categoryTabTextTransport: { color: Colors.teal },
  categoryTabTextToys:      { color: Colors.amber },
  categoryTabTextMedical:   { color: Colors.lime },
  categoryTabTextOther:     { color: Colors.deepText },

  itemsContainer: {
    backgroundColor: Colors.white,
    borderRadius: 20,
    shadowColor: Colors.pinkDeep,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: Colors.pinkBorder,
    overflow: 'hidden',
  },
  itemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 18,
    borderBottomWidth: 1,
    borderBottomColor: Colors.pinkLight,
    backgroundColor: Colors.white,
  },
  itemRowLast: { borderBottomWidth: 0 },
  itemRowChecked: { backgroundColor: Colors.pinkBg },

  checkbox: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: Colors.pinkLight,
    marginRight: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.white,
    shadowColor: Colors.pinkDeep,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  checkboxChecked: {
    backgroundColor: Colors.pink,
    borderColor: Colors.pink,
    shadowColor: Colors.pink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  checkboxIcon: { color: Colors.white, fontSize: 18, fontWeight: 'bold' },

  itemText: {
    flex: 1,
    fontSize: 16,
    color: Colors.purple,
    lineHeight: 24,
    fontWeight: '500',
  },
  itemTextChecked: {
    textDecorationLine: 'line-through',
    color: Colors.violet,
    fontStyle: 'italic',
  },

  categoryHeader: {
    backgroundColor: Colors.pinkBg,
    padding: 16,
    borderBottomWidth: 2,
    borderBottomColor: Colors.pinkLight,
  },
  categoryHeaderText: { fontSize: 20, fontWeight: 'bold', color: Colors.pink, textAlign: 'center' },

  emptyState: { alignItems: 'center', justifyContent: 'center', padding: 60 },
  emptyStateIcon: { fontSize: 48, color: Colors.violet, marginBottom: 16 },
  emptyStateText: { fontSize: 16, color: Colors.violet, textAlign: 'center', marginTop: 8, lineHeight: 22 },

  buttonsContainer: { flexDirection: 'row', justifyContent: 'center', marginTop: 24, paddingHorizontal: 4 },

  resetButton: {
    backgroundColor: Colors.red,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 15,
    shadowColor: Colors.red,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  resetButtonText: { color: Colors.white, fontSize: 16, fontWeight: 'bold', textAlign: 'center' },

  saveButton: {
    backgroundColor: Colors.green,
    paddingHorizontal: 24,
    paddingVertical: 16,
    borderRadius: 15,
    flex: 0.48,
    shadowColor: Colors.green,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 6,
  },
  saveButtonText: { color: Colors.white, fontSize: 16, fontWeight: 'bold', textAlign: 'center' },
  buttonHalf: { flex: 0.48 },

  decorativeLine: {
    height: 3,
    backgroundColor: Colors.pink,
    borderRadius: 2,
    marginVertical: 8,
    alignSelf: 'center',
    width: 60,
  },
  itemCountBadge: { backgroundColor: Colors.pink, borderRadius: 15, paddingHorizontal: 10, paddingVertical: 6, marginLeft: 8 },
  itemCountText: { color: Colors.white, fontSize: 12, fontWeight: 'bold' },
  categoryIcon: { marginRight: 8, fontSize: 18 },
});

export default babyChecklistStyles;
