// styles/<your-file>.js
import { StyleSheet } from 'react-native';
import { Colors } from '@/constants/Colors';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.pinkBg,
        padding: 20,
    },

    title: {
        textAlign: 'center',
        color: Colors.pinkDeep,
        fontSize: 28,
        fontWeight: 'bold',
        marginBottom: 8,
        textShadowColor: Colors.pinkShadowSoft,
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
    },
    subtitle: {
        textAlign: 'center',
        marginBottom: 25,
        fontSize: 16,
        color: Colors.mutedText,
        lineHeight: 22,
    },

    progressContainer: {
        backgroundColor: Colors.white,
        borderRadius: 15,
        padding: 20,
        marginBottom: 20,
        shadowColor: Colors.pinkDeep,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
    },
    progressTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: Colors.pinkDeep,
        textAlign: 'center',
        marginBottom: 15,
    },
    progressBar: {
        height: 12,
        backgroundColor: Colors.pinkLight,
        borderRadius: 6,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: Colors.pinkDeep,
        borderRadius: 6,
    },
    progressText: {
        textAlign: 'center',
        marginTop: 10,
        fontSize: 14,
        color: Colors.mutedText,
        fontWeight: '500',
    },

    tabsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        marginBottom: 20,
        gap: 8,
    },
    categoryTab: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        marginHorizontal: 4,
        marginBottom: 8,
        shadowColor: Colors.pinkDeep,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    categoryTabActive:   { backgroundColor: Colors.pinkDeep },
    categoryTabHygiene:  { backgroundColor: Colors.greenBg },
    categoryTabClothing: { backgroundColor: Colors.orangeBg },
    categoryTabMedical:  { backgroundColor: Colors.pinkLight },
    categoryTabBaby:     { backgroundColor: Colors.blueBg },

    categoryTabText: { fontSize: 14, fontWeight: '600', textAlign: 'center' },
    categoryTabTextActive:  { color: Colors.white },
    categoryTabTextHygiene: { color: Colors.green },
    categoryTabTextClothing:{ color: Colors.orange },
    categoryTabTextMedical: { color: Colors.pink },
    categoryTabTextBaby:    { color: Colors.blue },

    itemsContainer: { flex: 1 },

    itemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.white,
        paddingHorizontal: 20,
        paddingVertical: 16,
        marginBottom: 8,
        borderRadius: 12,
        shadowColor: Colors.pinkDeep,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    itemRowChecked: {
        backgroundColor: Colors.pinkLight,
        borderLeftWidth: 4,
        borderLeftColor: Colors.pinkDeep,
    },

    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: Colors.pinkDeep,
        marginRight: 15,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colors.white,
        shadowColor: Colors.pinkDeep,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 1,
    },
    checkboxChecked: { backgroundColor: Colors.pinkDeep, borderColor: Colors.pinkDeep },
    checkboxIcon: { color: Colors.white, fontSize: 16, fontWeight: 'bold' },

    itemText: { flex: 1, fontSize: 16, color: Colors.text, lineHeight: 22 },
    itemTextChecked: {
        color: Colors.pinkDeep,
        textDecorationLine: 'line-through',
        textDecorationColor: Colors.pinkDeep,
    },

    emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40 },
    emptyStateIcon: { fontSize: 48, marginBottom: 10 },
    emptyStateText: { fontSize: 16, color: Colors.mutedText, textAlign: 'center' },

    buttonsContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 20,
        marginBottom: 10,
    },
    resetButton: {
        backgroundColor: Colors.pinkDeep,
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 25,
        shadowColor: Colors.pinkDeep,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
    },
    resetButtonText: { color: Colors.white, fontSize: 16, fontWeight: 'bold', textAlign: 'center' },

    decorativeLine: {
        height: 3,
        backgroundColor: Colors.pinkDeep,
        borderRadius: 2,
        marginVertical: 15,
        opacity: 0.3,
    },

    itemCountBadge: {
        backgroundColor: Colors.pinkDeep,
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 2,
        marginLeft: 8,
        minWidth: 20,
        alignItems: 'center',
    },
    itemCountText: { color: Colors.white, fontSize: 12, fontWeight: 'bold' },
});
