import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff5f8', // Light pink background
        padding: 20,
    },
    title: {
        textAlign: 'center',
        color: '#d81b60', // Deep pink
        fontSize: 28,
        fontWeight: 'bold',
        marginBottom: 8,
        textShadowColor: 'rgba(216, 27, 96, 0.3)',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
    },
    subtitle: {
        textAlign: 'center',
        marginBottom: 25,
        fontSize: 16,
        color: '#666',
        lineHeight: 22,
    },
    progressContainer: {
        backgroundColor: '#fff',
        borderRadius: 15,
        padding: 20,
        marginBottom: 20,
        shadowColor: '#d81b60',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
    },
    progressTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#d81b60',
        textAlign: 'center',
        marginBottom: 15,
    },
    progressBar: {
        height: 12,
        backgroundColor: '#fce4ec',
        borderRadius: 6,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        backgroundColor: '#d81b60',
        borderRadius: 6,
    },
    progressText: {
        textAlign: 'center',
        marginTop: 10,
        fontSize: 14,
        color: '#666',
        fontWeight: '500',
    },
    tabsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        marginBottom: 20,
        gap: 8,
    },
    categoryTab: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        marginHorizontal: 4,
        marginBottom: 8,
        shadowColor: '#d81b60',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    categoryTabActive: {
        backgroundColor: '#d81b60',
    },
    categoryTabHygiene: {
        backgroundColor: '#e8f5e8',
    },
    categoryTabClothing: {
        backgroundColor: '#fff3e0',
    },
    categoryTabMedical: {
        backgroundColor: '#fce4ec',
    },
    categoryTabBaby: {
        backgroundColor: '#e3f2fd',
    },
    categoryTabText: {
        fontSize: 14,
        fontWeight: '600',
        textAlign: 'center',
    },
    categoryTabTextActive: {
        color: '#fff',
    },
    categoryTabTextHygiene: {
        color: '#2e7d32',
    },
    categoryTabTextClothing: {
        color: '#f57c00',
    },
    categoryTabTextMedical: {
        color: '#c2185b',
    },
    categoryTabTextBaby: {
        color: '#1976d2',
    },
    itemsContainer: {
        flex: 1,
    },
    itemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        paddingHorizontal: 20,
        paddingVertical: 16,
        marginBottom: 8,
        borderRadius: 12,
        shadowColor: '#d81b60',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    itemRowChecked: {
        backgroundColor: '#fce4ec',
        borderLeftWidth: 4,
        borderLeftColor: '#d81b60',
    },
    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: '#d81b60',
        marginRight: 15,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
        shadowColor: '#d81b60',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 1,
    },
    checkboxChecked: {
        backgroundColor: '#d81b60',
        borderColor: '#d81b60',
    },
    checkboxIcon: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    itemText: {
        flex: 1,
        fontSize: 16,
        color: '#333',
        lineHeight: 22,
    },
    itemTextChecked: {
        color: '#d81b60',
        textDecorationLine: 'line-through',
        textDecorationColor: '#d81b60',
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 40,
    },
    emptyStateIcon: {
        fontSize: 48,
        marginBottom: 10,
    },
    emptyStateText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
    },
    buttonsContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 20,
        marginBottom: 10,
    },
    resetButton: {
        backgroundColor: '#d81b60',
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 25,
        shadowColor: '#d81b60',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
    },
    resetButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    decorativeLine: {
        height: 3,
        backgroundColor: '#d81b60',
        borderRadius: 2,
        marginVertical: 15,
        opacity: 0.3,
    },
    itemCountBadge: {
        backgroundColor: '#d81b60',
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 2,
        marginLeft: 8,
        minWidth: 20,
        alignItems: 'center',
    },
    itemCountText: {
        color: '#fff',
        fontSize: 12,
        fontWeight: 'bold',
    },
});
