// styles/<your-file>.js
import { StyleSheet } from 'react-native';
import { Colors } from '../constants/Colors';

export default StyleSheet.create({
    centeredBox: {
        width: '90%',
        maxWidth: 600,
        alignSelf: 'center',
    },
    container: {
        flex: 1,
        backgroundColor: Colors.pink100,
        padding: 20,
    },

    header: {
        backgroundColor: Colors.blueLight,
        padding: 24,
        borderRadius: 20,
        marginBottom: 20,
        shadowColor: Colors.blue,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 1,
        borderColor: Colors.blue,
    },
    title: {
        textAlign: 'center',
        color: Colors.pink700,
        fontSize: 28,
        fontWeight: 'bold',
        marginBottom: 8,
        textShadowColor: Colors.pink700,
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    subtitle: {
        textAlign: 'center',
        marginBottom: 20,
        fontSize: 16,
        color: Colors.pink700,
        lineHeight: 22,
    },
    decorativeLine: {
        height: 3,
        backgroundColor: Colors.blue,
        borderRadius: 2,
        marginVertical: 8,
        alignSelf: 'center',
        width: 60,
    },

    progressContainer: { marginBottom: 20 },

    progressBar: {
        height: 12,
        backgroundColor: Colors.purpleLight,
        borderRadius: 10,
        overflow: 'hidden',
        shadowColor: Colors.purple,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    progressFill: {
        height: '100%',
        backgroundColor: Colors.pink,
        borderRadius: 10,
        shadowColor: Colors.pink,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    progressText: {
        textAlign: 'center',
        marginTop: 12,
        fontSize: 14,
        color: Colors.pink700,
        fontWeight: '600',
    },

    tabsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        marginBottom: 20,
        gap: 8,
        backgroundColor: Colors.blueLight,
        borderRadius: 20,
        padding: 16,
        shadowColor: Colors.blue,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 1,
        borderColor: Colors.blue,
    },
    categoryTab: {
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 20,
        marginHorizontal: 4,
        marginBottom: 8,
        shadowColor: Colors.pinkDeep,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        backgroundColor: Colors.pinkLight,
        borderWidth: 2,
        borderColor: Colors.pink,
    },
    categoryTabActive:   { 
        backgroundColor: Colors.blue,
        borderColor: Colors.blue,
        shadowColor: Colors.blue,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
    },

    categoryTabText: { 
        fontSize: 14, 
        fontWeight: '600', 
        textAlign: 'center',
        color: Colors.pink700,
    },
    categoryTabTextActive:  { 
        color: Colors.white,
        fontWeight: 'bold',
    },
    categoryTabContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    categoryTabIcon: {
        fontSize: 20,
        marginRight: 8,
    },

    itemsContainer: { 
        flex: 1,
        backgroundColor: Colors.blueLight,
        borderRadius: 20,
        shadowColor: Colors.blue,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 8,
        borderWidth: 1,
        borderColor: Colors.blue,
        overflow: 'hidden',
    },

    itemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: Colors.blueLight,
        paddingHorizontal: 20,
        paddingVertical: 16,
        marginBottom: 8,
        borderRadius: 12,
        shadowColor: Colors.blue,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
        borderBottomWidth: 1,
        borderBottomColor: Colors.pinkLight,
    },
    itemRowChecked: {
        backgroundColor: Colors.pink100,
        borderLeftWidth: 4,
        borderLeftColor: Colors.pink,
    },

    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: Colors.pinkLight,
        marginRight: 15,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: Colors.white,
        shadowColor: Colors.pinkDeep,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 1,
    },
    checkboxChecked: { 
        backgroundColor: Colors.blue, 
        borderColor: Colors.blue,
        shadowColor: Colors.blue,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    checkboxIcon: { color: Colors.white, fontSize: 16, fontWeight: 'bold' },

    itemText: { 
        flex: 1, 
        fontSize: 16, 
        color: Colors.blue700, 
        lineHeight: 22,
        fontWeight: '500',
    },
    itemTextChecked: {
        color: Colors.blue700,
        textDecorationLine: 'line-through',
        textDecorationColor: Colors.blue700,
        fontStyle: 'italic',
    },

    emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 40 },
    emptyStateIcon: { fontSize: 48, marginBottom: 10, color: Colors.blue700 },
    emptyStateText: { fontSize: 16, color: Colors.blue700, textAlign: 'center', lineHeight: 22 },

    buttonsContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        marginTop: 20,
        marginBottom: 10,
    },
    resetButton: {
        backgroundColor: Colors.blue,
        paddingHorizontal: 24,
        paddingVertical: 12,
        borderRadius: 25,
        shadowColor: Colors.blue,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 4,
    },
    resetButtonText: { color: Colors.white, fontSize: 16, fontWeight: 'bold', textAlign: 'center' },

    decorativeLine: {
        height: 3,
        backgroundColor: Colors.blue,
        borderRadius: 2,
        marginVertical: 15,
        opacity: 0.3,
    },

    itemCountBadge: {
        backgroundColor: Colors.blue,
        borderRadius: 12,
        paddingHorizontal: 8,
        paddingVertical: 2,
        marginLeft: 8,
        minWidth: 20,
        alignItems: 'center',
    },
    itemCountText: { color: Colors.white, fontSize: 12, fontWeight: 'bold' },
});
