import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    card: {
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 12,
        writingDirection: 'rtl',
        margin: 10,
        shadowColor: '#d81b60',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    itemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff',
        paddingHorizontal: 20,
        paddingVertical: 16,
        marginBottom: 8,
        borderRadius: 12,
        shadowColor: '#d81b60',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 4,
        elevation: 2,
    },
    itemRowChecked: {
        backgroundColor: '#fce4ec',
        borderLeftWidth: 4,
        borderLeftColor: '#d81b60',
    },
    itemText: {
        flex: 1,
        fontSize: 16,
        color: '#333',
        lineHeight: 22,
    },
    itemTextChecked: {
        color: '#d81b60',
        textDecorationLine: 'line-through',
        textDecorationColor: '#d81b60',
    },
    checkbox: {
        width: 24,
        height: 24,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: '#d81b60',
        marginRight: 15,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
        shadowColor: '#d81b60',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
        elevation: 1,
    },
    checkboxChecked: {
        backgroundColor: '#d81b60',
        borderColor: '#d81b60',
    },
    checkboxIcon: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    checked: {
        width: 12,
        height: 12,
        backgroundColor: '#d81b60',
    },
    categoryTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        textAlign: 'center',
        color: '#d81b60',
        marginBottom: 15,
    },
    emptyState: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 40,
    },
    emptyStateIcon: {
        fontSize: 48,
        marginBottom: 10,
    },
    emptyStateText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
    },
});
